volumes:
  pgdata:
    driver: local

services:
  backend:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - .:/code

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
