[project]
name = "uvenv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard,standart]>=0.115.12",
    "ruff>=0.11.12",
    "sqlmodel>=0.0.24",
]
